#!/usr/bin/env python3
"""Validate this marketplace and regenerate its README (Python standard library)."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def frontmatter(path):
    text = path.read_text(encoding="utf-8-sig")
    parts = text.split("---", 2)
    if len(parts) != 3 or parts[0].strip():
        raise ValueError("missing frontmatter")
    fields = {}
    # Repository convention: single-line scalar name and description.
    for line in parts[1].splitlines():
        match = re.match(r"^(name|description):\s*(.*)$", line)
        if match:
            key, value = match.groups()
            if key in fields:
                raise ValueError("duplicate frontmatter key: " + key)
            if value.startswith('"'):
                value = json.loads(value)
            elif value.startswith("'") and value.endswith("'"):
                value = value[1:-1].replace("''", "'")
            fields[key] = value.strip()
    return fields


def inventory(root):
    errors, plugins, seen = [], [], {}
    try:
        market = json.loads((root / ".claude-plugin/marketplace.json").read_text(encoding="utf-8"))
        entries = market["plugins"]
        if not isinstance(entries, list):
            raise ValueError("plugins must be an array")
    except (OSError, ValueError, KeyError) as exc:
        return [], ["marketplace: " + str(exc)]
    listed = set()
    for entry in entries:
        try:
            name, source = entry["name"], entry["source"]
            if name in listed:
                errors.append("duplicate plugin: " + name)
            listed.add(name)
            if not isinstance(source, str) or not source.startswith("./"):
                raise ValueError("expected local ./ plugin source")
            folder = (root / source).resolve()
            if not folder.is_relative_to(root.resolve()) or not folder.is_dir():
                raise ValueError("plugin does not exist within marketplace: " + source)
            manifest = json.loads((folder / ".claude-plugin/plugin.json").read_text(encoding="utf-8"))
            if manifest.get("name") != name:
                errors.append("plugin name mismatch: " + source)
            plugins.append((folder, manifest, []))
        except (OSError, ValueError, KeyError, TypeError) as exc:
            errors.append("plugin entry: " + str(exc))
    # Validate every on-disk plugin, not just marketplace-listed ones.
    known = {p[0] for p in plugins}
    for folder in sorted((root / "plugins").glob("*")):
        if folder.is_dir() and folder.resolve() not in known:
            errors.append("unlisted plugin: " + folder.name)
            plugins.append((folder, {"name": folder.name}, []))
    for folder, manifest, skills in plugins:
        for skill in sorted((folder / "skills").glob("*")):
            if not skill.is_dir():
                continue
            path = skill / "SKILL.md"
            if not path.is_file():
                errors.append(str(skill) + ": missing SKILL.md")
                continue
            try:
                fields = frontmatter(path)
                name = fields.get("name", "")
                if name != skill.name:
                    errors.append(str(path) + ": name != folder name")
                if not fields.get("description") or fields["description"] in ("null", "~", "|", ">"):
                    errors.append(str(path) + ": description missing or unsupported (use a single-line scalar)")
                if name in seen:
                    errors.append("duplicate skill name: " + name)
                seen[name] = path
                skills.append((path, fields))
            except (OSError, ValueError) as exc:
                errors.append(str(path) + ": " + str(exc))
    return plugins, errors


def readme(plugins, root):
    lines = ["# claude-toolkit", "", "Personal Claude Code plugin marketplace. Install only the bundles relevant to a project.", "", "<!-- Generated by scripts/gen-readme.sh. Edit scripts/marketplace.py instead. -->", "", "## Install", "", "Requires a current Claude Code version with plugin dependencies and exec-form hooks, Python 3.10+ and Bash (Git Bash on Windows).", "", "```text", "/plugin marketplace add Luqman-Ud-Din/claude-toolkit", "/plugin install audit-app@claude-toolkit --scope project", "/plugin install audit-llm@claude-toolkit --scope project", "/plugin install explore-app@claude-toolkit --scope project", "```", "", "Choose only the install lines you need. `audit-app` and `audit-llm` depend on `audit-core`, which Claude Code installs automatically. `explore-app` is independent. For a full-stack LLM app, install both audit bundles.", "", "Restart Claude Code after installing or updating so audit-core's SessionStart hook exports `AUDIT_CORE_ROOT` for subsequent **Bash** commands. Hooks must be enabled; review them in `/hooks`. No manual environment setup is needed for normal Claude Code Bash use. PowerShell or standalone terminal invocations must set `AUDIT_CORE_ROOT` to the installed core plugin directory explicitly. There is no cache search fallback.", "", "```text", "/audit-app:audit-application", "/audit-llm:audit-llm-application", "/explore-app:explore-application", "```", "", "For local development, load both dependency and consumer:", "", "```bash", "claude --plugin-dir ./plugins/audit-core --plugin-dir ./plugins/audit-app", "```", "", "## Maintenance", "", "```bash", "bash scripts/validate.sh", "bash scripts/gen-readme.sh", "python scripts/test_marketplace.py", "claude plugin validate .", "```", "", "The validator enforces single-line scalar `name` and `description` frontmatter, matching folder names, unique skill names, and existing marketplace plugin sources. Keep eval fixtures with their skill. Runtime audit outputs retain bare skill IDs, not plugin namespaces.", "", "## Known scope limitations", "", "The migration preserves audit logic. Existing LLM references to the absent `llm-audit-skills.md` design document remain unresolved; the conventional ASVS mapper does not implement LLM-standard coverage. LLM live probes require explicit target authorization. Installation tests do not constitute a live audit or a complete skill-eval run.", "", "## Plugin index", ""]
    insert_at = lines.index("## Plugin index")
    lines[insert_at:insert_at] = [
        "## Local fixture keys and push protection", "",
        "GitHub push protection blocked the initial import because Stripe key-shaped values occur in eval fixtures and the sensitive-data catalog. The mixed-sample fixture labels its values as synthetic; this is not verification that every flagged value is inactive. Do not bypass protection or paste full values into issues, PRs, or this README.", "",
        "The four flagged values are stored locally under `env` in the ignored `.claude/settings.local.json`. Tracked fixtures contain variable placeholders instead. The catalog optionally reads `TOOLKIT_DOC_STRIPE_TEST_KEY` from its environment to recognize that exact documentation example; without it, this one extra exemption is unavailable.", "",
        "For another checkout, preserve existing local settings and merge locally chosen synthetic values into `env`. The placeholders below are not credentials:", "",
        "```json",
        "{",
        '  "env": {',
        '    "TOOLKIT_FIXTURE_STRIPE_SECRET": "<local synthetic fixture value>",',
        '    "TOOLKIT_FIXTURE_STRIPE_CONFIG_SECRET": "<local synthetic config fixture value>",',
        '    "TOOLKIT_FIXTURE_STRIPE_PLACEHOLDER": "<local placeholder test value>",',
        '    "TOOLKIT_DOC_STRIPE_TEST_KEY": "<local provider-documentation test value>"',
        "  }",
        "}",
        "```", "",
        "`.claude/settings.local.json` is ignored by Git and must never be force-added. These variables are for fixture testing, not production Stripe access. They are unrelated to `AUDIT_CORE_ROOT`, which locates shared plugin scripts.", "",
        "Affected tracked files:", "",
        "- `plugins/audit-core/skills/audit-sensitive-data-catalog/evals/files/mixed-sample.txt`",
        "- `plugins/audit-core/skills/audit-sensitive-data-catalog/evals/evals.json`",
        "- `plugins/audit-core/skills/audit-sensitive-data-catalog/references/catalog.json`",
        "- `plugins/audit-app/skills/audit-secrets-and-config/evals/files/sample-repo/Api/appsettings.Production.json`", "",
        "Materialize fixtures with `python scripts/materialize_fixtures.py plugins/audit-core/skills/audit-sensitive-data-catalog/evals --local-settings .claude/settings.local.json` (or the audit-secrets-and-config eval directory). Run the eval against the printed temporary directory, then delete that directory: it contains the substituted local values. Missing values fail explicitly. The catalog uses the environment, not the settings file directly; restart Claude Code to load updated local environment settings, or supply the variable explicitly in standalone runs. Before pushing, remove the flagged literals from the unpublished commit history with approval, then rerun checks and push. A cleanup commit alone does not remove values from earlier commits. Rotate any value discovered to be a real credential.", "",
    ]
    for folder, manifest, skills in sorted(plugins, key=lambda row: row[1]["name"]):
        name = manifest["name"]
        lines.extend([f"### {name}", "", manifest.get("description", ""), "", f"Version: `{manifest.get('version', '')}` Â· Skills: {len(skills)}", "", "| Skill | Description |", "|---|---|"])
        for path, fields in skills:
            desc = fields["description"].replace("|", "&#124;").replace("\n", " ")
            rel = path.relative_to(root).as_posix()
            lines.append(f"| [{fields['name']}]({rel}) | {desc} |")
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=["validate", "readme"])
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    root = args.root.resolve()
    plugins, errors = inventory(root)
    if errors:
        print("\n".join("ERROR: " + error for error in errors))
        return 1
    if args.action == "readme":
        (root / "README.md").write_text(readme(plugins, root), encoding="utf-8", newline="\n")
        print("Generated README.md")
    else:
        print(f"PASS: {len(plugins)} plugins, {sum(len(row[2]) for row in plugins)} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
