#!/usr/bin/env python3
"""Load-test plan generator and results interpreter for audit-performance-and-scalability.

Sub-commands:

  k6      Generate a k6 script skeleton from an endpoint inventory JSON
          (audit-endpoint-inventory's endpoints.probe.json, or a hand-written file with
          the same "endpoints" list of route/method/kind/weight rows).
          python loadtest_plan.py k6 --inventory endpoints.probe.json --base-url https://host
                 [--rps 50] [--duration 10m] [--profile load|smoke|stress|soak]
                 [--thresholds references/thresholds.json] [--max-endpoints 25] [--out loadtest.js]

  grade   Grade a k6 or bombardier JSON summary against thresholds and print a
          Markdown results table with PASS/FAIL per metric.
          python loadtest_plan.py grade summary.json --format k6|bombardier
                 [--thresholds references/thresholds.json] [--kind read|write|default]
                 [--target-rps 50] [--out result.md]

Accepted summary shapes:
  k6 --summary-export:  {"metrics": {"http_req_duration": {"avg":..,"med":..,"p(90)":..,"p(95)":..,"p(99)"?..},
                                     "http_req_failed": {"value":.. | "rate":..}, "http_reqs": {"count":..,"rate":..}}}
  k6 handleSummary:     {"metrics": {"http_req_duration": {"values": {"p(95)":..}}, ...}}
  bombardier --format json: {"result": {"latency": {"mean":..,"percentiles": {"50":..,"95":..,"99":..}} (microseconds),
                                        "rps": {"mean":..}, "req2xx":.., "req4xx":.., "req5xx":.., "others":.., "errors":..}}
Per-endpoint k6 metrics (http_req_duration{name:...}) are graded individually when present.

Exit code: 0 PASS, 1 FAIL, 2 usage error. Read-only apart from --out.
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_THRESHOLDS = os.path.join(HERE, "..", "references", "thresholds.json")

PROFILES = {
    "smoke": {"executor": "constant-vus", "vus": 1, "duration": "1m"},
    "load": {"executor": "ramping-arrival-rate", "ramp": "2m", "hold": "10m"},
    "stress": {"executor": "ramping-arrival-rate", "ramp": "2m", "hold": "5m", "multiplier": 2},
    "soak": {"executor": "constant-arrival-rate", "hold": "30m"},
}


def load_thresholds(path):
    with open(path or DEFAULT_THRESHOLDS, "r", encoding="utf-8") as fh:
        return json.load(fh)


def gen_k6(a):
    with open(a.inventory, "r", encoding="utf-8") as fh:
        inv = json.load(fh)
    eps = inv.get("endpoints", inv if isinstance(inv, list) else [])
    eps = [e for e in eps if e.get("route")][: a.max_endpoints]
    if not eps:
        print("no endpoints in inventory", file=sys.stderr)
        return 2
    th = load_thresholds(a.thresholds)
    prof = PROFILES[a.profile]
    rps = a.rps * prof.get("multiplier", 1)
    total_w = sum(e.get("weight", 1) or 1 for e in eps)
    reads = th.get("read", th.get("default"))
    writes = th.get("write", th.get("default"))
    err = th.get("error_rate_max", 0.01)

    lines = ["// k6 skeleton generated by audit-performance-and-scalability/scripts/loadtest_plan.py",
             "// Fill in: auth (TOKEN env), request bodies for write endpoints, path params, think time.",
             "import http from 'k6/http';", "import { check, sleep, group } from 'k6';", "",
             f"const BASE = __ENV.BASE || '{a.base_url.rstrip('/')}';",
             "const TOKEN = __ENV.TOKEN || '';",
             "const HEADERS = { 'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, br', ...(TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {}) };", "",
             "// endpoint mix: weight = share of requests; kind decides the threshold bucket",
             "const ENDPOINTS = ["]
    for e in eps:
        route = e["route"].replace("{controller}", "controller")
        body = "null" if e.get("kind") == "read" else "JSON.stringify({ /* TODO body for " + route + " */ })"
        lines.append(f"  {{ name: '{e['method']} {route}', method: '{e['method']}', path: '{route}', kind: '{e.get('kind', 'read')}', weight: {e.get('weight', 1) or 1}, body: {body} }},")
    lines += ["];", f"const TOTAL_WEIGHT = {total_w};", "",
              "function pick() { let r = Math.random() * TOTAL_WEIGHT; for (const e of ENDPOINTS) { r -= e.weight; if (r <= 0) return e; } return ENDPOINTS[0]; }", "",
              "export const options = {",
              "  summaryTrendStats: ['avg', 'med', 'p(90)', 'p(95)', 'p(99)', 'max'],",
              "  systemTags: ['status', 'method', 'name', 'url', 'error', 'scenario'],",
              "  scenarios: {"]
    if prof["executor"] == "constant-vus":
        lines.append(f"    {a.profile}: {{ executor: 'constant-vus', vus: {prof['vus']}, duration: '{prof['duration']}' }},")
    elif prof["executor"] == "constant-arrival-rate":
        lines.append(f"    {a.profile}: {{ executor: 'constant-arrival-rate', rate: {rps}, timeUnit: '1s', duration: '{a.duration or prof['hold']}', preAllocatedVUs: {max(10, rps)}, maxVUs: {max(50, rps * 4)} }},")
    else:
        lines.append(f"    {a.profile}: {{ executor: 'ramping-arrival-rate', startRate: {max(1, rps // 10)}, timeUnit: '1s', preAllocatedVUs: {max(10, rps)}, maxVUs: {max(50, rps * 4)},")
        lines.append(f"      stages: [ {{ target: {rps}, duration: '{prof['ramp']}' }}, {{ target: {rps}, duration: '{a.duration or prof['hold']}' }}, {{ target: 0, duration: '30s' }} ] }},")
    lines += ["  },", "  thresholds: {",
              f"    http_req_failed: ['rate<{err}'],",
              f"    'http_req_duration{{kind:read}}': ['p(50)<{reads['p50_ms']}', 'p(95)<{reads['p95_ms']}', 'p(99)<{reads['p99_ms']}'],",
              f"    'http_req_duration{{kind:write}}': ['p(50)<{writes['p50_ms']}', 'p(95)<{writes['p95_ms']}', 'p(99)<{writes['p99_ms']}'],"]
    for e in eps:
        route = e["route"].replace("{controller}", "controller")
        b = reads if e.get("kind") == "read" else writes
        lines.append(f"    'http_req_duration{{name:{e['method']} {route}}}': ['p(95)<{b['p95_ms']}'],")
    lines += ["  },", "};", "",
              "export default function () {",
              "  const e = pick();",
              "  const url = `${BASE}${e.path}`.replace(/\\{(\\w+)\\}|:(\\w+)/g, '1'); // TODO real ids per param",
              "  const params = { headers: HEADERS, tags: { name: e.name, kind: e.kind }, timeout: '30s' };",
              "  const res = e.method === 'GET' ? http.get(url, params)",
              "            : e.method === 'DELETE' ? http.del(url, null, params)",
              "            : http.request(e.method, url, e.body, params);",
              "  check(res, { 'status 2xx/3xx': r => r.status >= 200 && r.status < 400 });",
              "  sleep(Math.random() * 0.5); // think time; remove for pure arrival-rate tests",
              "}", "",
              "export function handleSummary(data) {",
              "  return { 'summary.json': JSON.stringify(data, null, 2), stdout: textSummary(data) };",
              "}",
              "function textSummary(d) { const m = d.metrics.http_req_duration; const v = m.values || m; return `p50=${v.med} p95=${v['p(95)']} p99=${v['p(99)']} failed=${(d.metrics.http_req_failed.values||d.metrics.http_req_failed).rate}\\n`; }",
              "", f"// run: k6 run -e BASE={a.base_url} -e TOKEN=$TOKEN --summary-export=summary-legacy.json {os.path.basename(a.out) if a.out else 'loadtest.js'}",
              "// grade: python scripts/loadtest_plan.py grade summary.json --format k6"]
    text = "\n".join(lines) + "\n"
    if a.out:
        os.makedirs(os.path.dirname(os.path.abspath(a.out)) or ".", exist_ok=True)
        with open(a.out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(a.out)
    else:
        print(text)
    return 0


def _vals(metric):
    if not isinstance(metric, dict):
        return {}
    return metric.get("values", metric)


def _get(v, *keys):
    for k in keys:
        if k in v and v[k] is not None:
            return float(v[k])
    return None


def parse_k6(doc):
    metrics = doc.get("metrics", {})
    out = {"overall": {}, "per_endpoint": {}}
    for name, m in metrics.items():
        if name == "http_req_duration" or name.startswith("http_req_duration{"):
            v = _vals(m)
            entry = {"p50": _get(v, "med", "p(50)"), "p95": _get(v, "p(95)"), "p99": _get(v, "p(99)"), "avg": _get(v, "avg")}
            if name == "http_req_duration":
                out["overall"].update(entry)
            else:
                tag = name[len("http_req_duration{"):-1]
                out["per_endpoint"][tag] = entry
        elif name == "http_req_failed":
            v = _vals(m)
            out["overall"]["error_rate"] = _get(v, "rate", "value")
        elif name == "http_reqs":
            v = _vals(m)
            out["overall"]["rps"] = _get(v, "rate")
            out["overall"]["count"] = _get(v, "count")
    return out


def parse_bombardier(doc):
    r = doc.get("result", doc)
    lat = r.get("latency", {})
    pct = lat.get("percentiles", {})
    us = lambda x: None if x is None else float(x) / 1000.0  # microseconds -> ms
    total = sum(float(r.get(k, 0) or 0) for k in ("req1xx", "req2xx", "req3xx", "req4xx", "req5xx", "others"))
    bad = float(r.get("req4xx", 0) or 0) + float(r.get("req5xx", 0) or 0) + float(r.get("others", 0) or 0)
    return {"overall": {"p50": us(pct.get("50")), "p95": us(pct.get("95")), "p99": us(pct.get("99")), "avg": us(lat.get("mean")),
                        "error_rate": (bad / total) if total else None, "rps": float((r.get("rps") or {}).get("mean", 0) or 0), "count": total},
            "per_endpoint": {}}


def grade(a):
    th = load_thresholds(a.thresholds)
    with open(a.path, "r", encoding="utf-8") as fh:
        doc = json.load(fh)
    parsed = parse_k6(doc) if a.format == "k6" else parse_bombardier(doc)
    bucket = th.get(a.kind, th.get("default"))
    err_max = th.get("error_rate_max", 0.01)
    target_rps = a.target_rps or th.get("throughput_min_rps")
    rows = []

    def judge(label, val, limit, unit="ms", lower_is_better=True):
        if val is None:
            rows.append((label, "not measured", f"{limit} {unit}" if limit is not None else "-", "NOT MEASURED"))
            return
        ok = (val <= limit) if lower_is_better else (val >= limit)
        rows.append((label, f"{val:.1f} {unit}" if unit == "ms" else f"{val:.3f}" if unit == "" else f"{val:.1f} {unit}", f"{'<=' if lower_is_better else '>='} {limit} {unit}", "PASS" if ok else "FAIL"))

    o = parsed["overall"]
    judge("p50 latency", o.get("p50"), bucket["p50_ms"])
    judge("p95 latency", o.get("p95"), bucket["p95_ms"])
    judge("p99 latency", o.get("p99"), bucket["p99_ms"])
    judge("Error rate", o.get("error_rate"), err_max, unit="")
    if target_rps:
        judge("Throughput", o.get("rps"), float(target_rps), unit="rps", lower_is_better=False)
    else:
        rows.append(("Throughput", f"{o.get('rps', 0) or 0:.1f} rps" if o.get("rps") is not None else "not measured", "no target set (--target-rps)", "INFO"))

    ep_rows = []
    for tag, e in sorted(parsed["per_endpoint"].items()):
        kind = "write" if "kind:write" in tag else ("read" if "kind:read" in tag else a.kind)
        b = th.get(kind, th.get("default"))
        verdict = "NOT MEASURED" if e.get("p95") is None else ("PASS" if e["p95"] <= b["p95_ms"] else "FAIL")
        ep_rows.append((tag, e.get("p50"), e.get("p95"), e.get("p99"), b["p95_ms"], verdict))

    overall = "FAIL" if any(r[3] == "FAIL" for r in rows) or any(r[5] == "FAIL" for r in ep_rows) else "PASS"
    out = [f"### Load-test results ({os.path.basename(a.path)}, {a.format}, bucket={a.kind})", "",
           "| Metric | Observed | Threshold | Verdict |", "|---|---|---|---|"]
    out += [f"| {m} | {v} | {t} | {r} |" for m, v, t, r in rows]
    if ep_rows:
        out += ["", "| Endpoint tag | p50 | p95 | p99 | p95 threshold | Verdict |", "|---|---|---|---|---|---|"]
        fmt = lambda x: "-" if x is None else f"{x:.0f}"
        out += [f"| {t} | {fmt(p50)} | {fmt(p95)} | {fmt(p99)} | {lim} | {v} |" for t, p50, p95, p99, lim, v in ep_rows]
    out += ["", f"**Overall: {overall}**", "",
            "FAIL on latency with low CPU -> waiting (pool, lock, sequential upstream, sync-over-async); with high CPU -> profile. "
            "FAIL on error rate at a fixed concurrency -> pool/thread limits. See references/load-test-tools.md 'Interpreting'."]
    text = "\n".join(out)
    if a.out:
        os.makedirs(os.path.dirname(os.path.abspath(a.out)) or ".", exist_ok=True)
        with open(a.out, "w", encoding="utf-8") as fh:
            fh.write(text + "\n")
        print(a.out)
    else:
        print(text)
    return 0 if overall == "PASS" else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("k6")
    p.add_argument("--inventory", required=True)
    p.add_argument("--base-url", default="https://localhost:5001")
    p.add_argument("--rps", type=int, default=50)
    p.add_argument("--duration", default=None, help="hold duration, e.g. 10m")
    p.add_argument("--profile", choices=sorted(PROFILES), default="load")
    p.add_argument("--thresholds", default=None)
    p.add_argument("--max-endpoints", type=int, default=25)
    p.add_argument("--out")
    p = sub.add_parser("grade")
    p.add_argument("path")
    p.add_argument("--format", choices=["k6", "bombardier"], default="k6")
    p.add_argument("--thresholds", default=None)
    p.add_argument("--kind", choices=["read", "write", "default"], default="default")
    p.add_argument("--target-rps", type=float, default=None)
    p.add_argument("--out")
    a = ap.parse_args()
    return gen_k6(a) if a.cmd == "k6" else grade(a)


if __name__ == "__main__":
    sys.exit(main())
